### ISSUE TITLE
Errors:can't install cgilua

### ISSUE THREAD

**Issue by JuanRuiz** [keplerproject/luarocks#482] opened 2016-01-08 17:03 UTC
/usr/share/lua/5.1/luarocks/deps.lua:159: attempt to compare two table values
stack traceback:
        /usr/share/lua/5.1/luarocks/deps.lua:159: in function 'compare_versions'
        /usr/share/lua/5.1/luarocks/type_check.lua:175: in function 'check_version'
        /usr/share/lua/5.1/luarocks/type_check.lua:269: in function </usr/share/lua/5.1/luarocks/type_check.lua:264>
        (tail call): ?
        /usr/share/lua/5.1/luarocks/manif_core.lua:28: in function </usr/share/lua/5.1/luarocks/manif_core.lua:21>
        (tail call): ?
        /usr/share/lua/5.1/luarocks/search.lua:176: in function 'manifest_search'
        /usr/share/lua/5.1/luarocks/search.lua:209: in function 'search_repos'
        /usr/share/lua/5.1/luarocks/search.lua:285: in function 'find_suitable_rock'
        /usr/share/lua/5.1/luarocks/install.lua:189: in function </usr/share/lua/5.1/luarocks/install.lua:161>
        (tail call): ?
        [C]: in function 'xpcall'
        /usr/share/lua/5.1/luarocks/command_line.lua:208: in function 'run_command'
        /usr/bin/luarocks:33: in main chunk
        [C]: ?

**Comment by mpeterv** [comment] 2016-01-08 17:16
Can't reproduce, what versions of Lua and LuaRocks do you use?

**Comment by JuanRuiz** [comment] 2016-01-08 18:05
hi mpeterv,
versions are 
lua 5.1 and LuaRocks 2.2.2

**Comment by ignacio** [comment] 2016-01-31 18:58
Couldn't reproduce with Lua 5.1 and LuaRocks 2.3.0

**Comment by JuanRuiz** [comment] 2016-01-31 19:03
I'm using LuaRocks 2.2.2

**Comment by ignacio** [comment] 2016-02-08 21:16
Can you give 2.3.0 a try? What other rocks do you have installed? (luarocks list)

**Comment by JuanRuiz** [comment] 2016-02-09 13:34
Hi,
I can use lua but I can't luarocks.
I want to install cgilua, "luarocks install cgilua"
Regards,

**Comment by wardg32** [comment] 2016-06-15 23:30
FYI the same error here trying to install lua-mosquitto on OpenWRT.

root@OpenWRT:~# luarocks install lua-mosquitto

Error: LuaRocks 2.2.2 bug (please report at https://github.com/keplerproject/luarocks/issues).
/usr/share/lua/5.1/luarocks/deps.lua:159: attempt to compare two table values
stack traceback:
	/usr/share/lua/5.1/luarocks/deps.lua:159: in function 'compare_versions'
	/usr/share/lua/5.1/luarocks/type_check.lua:175: in function 'check_version'
	/usr/share/lua/5.1/luarocks/type_check.lua:269: in function </usr/share/lua/5.1/luarocks/type_check.lua:264>
	(tail call): ?
	/usr/share/lua/5.1/luarocks/manif_core.lua:28: in function </usr/share/lua/5.1/luarocks/manif_core.lua:21>
	(tail call): ?
	/usr/share/lua/5.1/luarocks/search.lua:176: in function 'manifest_search'
	/usr/share/lua/5.1/luarocks/search.lua:209: in function 'search_repos'
	/usr/share/lua/5.1/luarocks/search.lua:285: in function 'find_suitable_rock'
	/usr/share/lua/5.1/luarocks/install.lua:189: in function </usr/share/lua/5.1/luarocks/install.lua:161>
	(tail call): ?
	[C]: in function 'xpcall'
	/usr/share/lua/5.1/luarocks/command_line.lua:208: in function 'run_command'
	/usr/bin/luarocks:33: in main chunk
	[C]: ?
root@OpenWRT:~# 

root@OpenWRT:~# luarocks list
Warning: Failed loading manifest for /root/.luarocks/lib/luarocks/rocks: /root/.luarocks/lib/luarocks/rocks/manifest: No such file or directory
Warning: Failed loading manifest for /usr/lib/luarocks/rocks: /usr/lib/luarocks/rocks/manifest: No such file or directory

Running Lua 5.1 and Luarocks 2.2.2. as unfortunately that's what the openwrt package is.

**Comment by hishamhm** [comment] 2016-06-16 00:09
@wardg32 can you re-run the command with --verbose and paste the full output? (you may use gist.github.com for that)

**Comment by wardg32** [comment] 2016-06-16 18:25
[Here you go](https://gist.github.com/wardg32/9a445f9c7b73a290aa24e32369db58f4), hope it helps.

**Comment by che** [comment] 2016-07-17 15:01
On this moment Luarocks (version 2.2.2) does not work for all Lua packages on OpenWRT.

root@OpenWrt:/# lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio **(double int32)**
> local m = { __lt = function( o1, o2 ) return 'lt' end, __eq = function( o1, o2 ) return 'eq' end }
> t1 = {}
> t2 = {} 
> setmetatable(t1, m)
> setmetatable(t2, m)
> print(t1 < t2)
stdin:1: attempt to compare two table values
stack traceback:
	stdin:1: in main chunk
	[C]: ?
> print(t1 == t2)
false
>

On Linux server 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux:
user@server:~$ lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> local m = { __lt = function( o1, o2 ) return 'whee' end, __eq = function( o1, o2 ) return 'w' end }
> t1 = {}
> setmetatable(t1, m)
> t2 = {}
> setmetatable(t2, m)
> print(t1 < t2)
true
> print(t1 == t2)
true
>

**Comment by daurnimator** [comment] 2016-07-17 21:20
@che see https://dev.openwrt.org/ticket/20821

**Comment by che** [comment] 2016-07-18 00:11
Thank a lot!

**Comment by Onuonga** [comment] 2016-09-09 09:03
Did anyone ever get a way of solving this? It seems from the above post that the version(s) of lua are different. I would not mind following up with the openwrt team and specifically whoever maintains Lua there.

**Comment by mpeterv** [comment] 2016-10-31 22:08
Looking at the ticket above this is indeed an issue with openwrt and their team knows (the ticket is still open though). Closing as not a luarocks bug.

**Closed by mpeterv** 2016-10-31 22:08 UTC
