### ISSUE TITLE
source.tag versus source.branch fields in rockspecs?

### ISSUE THREAD

**Issue by telemachus** [keplerproject/luarocks#409] opened 2015-07-10 18:45 UTC
I'm trying to install a rock using the following rockspec:

    package = 'tapered'
    version = '1.0-1'
    source = {
        url = 'git+https://bitbucket.org/telemachus/tapered.git',
        tag = '1.0-1'
    }
    description = {
        homepage = 'https://bitbucket.org/telemachus/tapered',
        summary = 'Very minimal tap testing for Lua.',
        detailed = [[
    	Very minimal tap testing for Lua. Arguably too minimal.
        ]],
        license = 'BSD 3-Clause',
        maintainer = 'Peter Aronoff <telemachus@arpinum.org>',
    }
    dependencies = {
        'lua >= 5.1'
    }
    build = {
        type = 'builtin',
        modules = { tapered = 'src/tapered.lua' },
        copy_directories = { 'doc' }
    }

My problem is that adding the `source.tag` field causes `luarock` to issue this command:

    git clone -- --branch=1.0-1 https://bitbucket.org/telemachus/tapered.git tapered

That in turn leads `git` to fail, complaining "Too many arguments." (Full output of the attempted install with `--verbose` [gisted here](https://gist.github.com/telemachus/8411d56825f4e3d29936).)

My question is: Why does `source.tag` work this way? I would expect that outcome for `source.branch` instead. For `git`, to checkout a tag, you first need to `cd` into the target directory and then run `git checkout <tag>`.

**Comment by mpeterv** [comment] 2015-07-10 18:51
`--branch` accepts tags since git 1.7.10, the issue is that `--branch` option is inserted after `--`, not before, hence git thinks it's another argument.

**Comment by telemachus** [comment] 2015-07-10 18:52
@mpeterv I didn't realize that change in `git`. Thanks for clarifying.

Still, I wonder what `luarocks` should do. Maybe it's safer to `cd` since that behavior works for any version of `git`?

**Comment by ignacio** [comment] 2015-07-10 18:52
Yes. It seems that the git+http protocol is the culprit here. Could you try with  `url = 'https://bitbucket.org/telemachus/tapered.git'`

**Comment by telemachus** [comment] 2015-07-10 18:53
@ignacio That didn't seem to work for me. It led `luarocks` to use `wget` as I recall. I can try again though.

**Comment by telemachus** [comment] 2015-07-10 18:57
@ignacio Unfortunately if I remove 'git+', then `luarocks` tries to use `curl` and things go badly:

    $ brewdo do luarocks install --verbose tapered-1.0-1.rockspec 
    Using tapered-1.0-1.rockspec... switching to 'build' mode
    
    os.execute: 	'curl' -k -f -L --user-agent 'LuaRocks/2.2.2 macosx-x86_64 via curl' --connect-timeout 30 'https://bitbucket.org/telemachus/tapered.git' 2> /dev/null 1> '/private/tmp/luarocks_luarocks-source-tapered-1.0-1-5801/tapered.git'
    Results: 3
      1 (boolean): true
      2 (string): exit
      3 (number): 0
    
    Error: Directory tapered not found inside archive tapered.git

**Comment by mpeterv** [comment] 2015-07-10 18:59
@telemachus luarocks checks git version, e.g. on my machine it uses separate checkout command because I have git 1.7.9.

I think the easiest fix is to change 4 to 3 in `table.insert(command, 4, "--branch=" .. tag_or_branch)` in luarocks.fetch.git module

**Comment by telemachus** [comment] 2015-07-10 19:01
@mpeterv And *that's* what I get for not checking the source code! Thanks again.

**Comment by ignacio** [comment] 2015-07-10 19:02
@telemachus Ok, I'll look into it.
@mpeterv I *think* that it is not that easy. The number of arguments seems to change whether you're using git:// or git+http(s):// protocols. I also look into that.

**Comment by mpeterv** [comment] 2015-07-10 19:08
@ignacio http or https protocols can't be used for cloning because curl or wget will simply return some html from the project page, so that error is not an issue.

**Comment by ignacio** [comment] 2015-07-10 19:10
@mpeterv is that a BitBucket thing, right?

**Comment by telemachus** [comment] 2015-07-10 19:10
@mpeterv I wondered about this as well. If the url ends in `.git`, I was surprised that `curl` or `wget` was chosen for download instead of `git`.

@ignacio What do you mean by "that" being a Bitbucket thing? Not sure I follow.

**Comment by mpeterv** [comment] 2015-07-10 19:11
@ignacio maybe you mean using 'git' protocol, not 'https'?

**Comment by ignacio** [comment] 2015-07-10 20:47
Sorry for the delay.
Yes, @mpeterv that's what I wanted to say. 

@telemachus The original trouble you had (on Twitter) was related to using url = "https://blabla.git", right?  I wonder if we can (safely) issue a warning when http(s) points to a .git repository.

**Comment by telemachus** [comment] 2015-07-10 20:57
@ignacio I think so, but I'm not sure. I had a lot of trouble, and I kept trying different values for `source.url` and other fields to fix things. I was trying following [this guide](https://github.com/keplerproject/luarocks/wiki/Creating-a-rock#Publishing_your_code_online), but it doesn't mention the 'git+http{s}' options. (I found those later when googling.)

I'm not really sure whether I was confused or if the documentation is confusing—or both! I'll read over it again when I can and maybe submit some ideas for clarifications there. In any case, thanks both of you for your help.

**Comment by ignacio** [comment] 2015-07-13 15:04
Makes sense. Since you use Bitbucket, do you know if the same applies to Mercurial repos?

**Comment by telemachus** [comment] 2015-07-13 15:13
@ignacio I must be one of the few, but although I use Bitbucket, I never use Mercurial. So I'm not sure. Sorry.

**Comment by siffiejoe** [comment] 2015-07-13 16:37
> I was trying following this guide, but it doesn't mention the 'git+http{s}' options. (I found those later when googling.)

That's because those options are recent additions that don't work on older LuaRocks versions (`git+http` doesn't work before 2.2.0, `git+https` doesn't work before 2.2.2). This is one of the few cases (the only case?) where Hisham let incompatible changes slip through ...

**Comment by telemachus** [comment] 2015-07-13 16:40
@siffiejoe Fair enough. I suppose for earlier versions of LuaRocks then, the easiest thing on Bitbucket is to upload a tar.gz file (which is what I did initially). Unlike GitHub, Bitbucket doesn't provide git:// as a protocol; only ssh:// and https:// are available.

**Comment by hishamhm** [comment] 2015-07-13 17:27
> This is one of the few cases (the only case?) where Hisham let incompatible changes slip through ...

Yes, I made an exception for fetch protocols because these fail with a nice error message saying that "git+https is an unsupported protocol". Consider this a point where LuaRocks 2 is "extensible". The other point is build types, where you can come up with any build.type="foo" as long as a module `luarocks.build.foo` exists (and it can even be fetched via a dependency).

**Comment by hishamhm** [comment] 2015-07-13 17:30
So if I followed correctly the problem was that `--branch` was inserted in the wrong place. Did #410 fix it? Can we close this one?

**Comment by ignacio** [comment] 2015-07-13 17:32
Yes, 410 fixed it. Didn't close this one because I thought about adding what @telemachus suggested here: https://github.com/keplerproject/luarocks/issues/409#issuecomment-120524244

What do you think?

**Comment by hishamhm** [comment] 2015-07-13 18:10
I'd skip that for now. It would break the mapping between `protocol://` and `luarocks.fetch.protocol` module...

**Comment by ignacio** [comment] 2015-07-13 18:10
Oh, right. Closing then.

**Closed by ignacio** 2015-07-13 18:10 UTC
