### ISSUE TITLE
Error message on Windows when (re-)installing multiple versions of a rock

### ISSUE THREAD

**Issue by siffiejoe** [keplerproject/luarocks#268] opened 2014-05-28 21:32 UTC
The following sequence
```
luarocks install luafilesystem
luarocks install luafilesystem 1.6.1 --keep
luarocks install luafilesystem
```
on Windows leads to the error message
```
Removing luafilesystem 1.6.1-1...
C:\LR4Win\tools\cp.exe: cannot stat `C:\\LR4Win\\luarocks\\lib\\lua\\5.2\\luafilesystem_1_6_1_1-lfs.dll': No such file or directory
Removal successful.
```
After the first install I have `lfs.dll` (for version 1.6.2 of luafilesystem), after the second call I have `lfs.dll` and `luafilesystem_1_6_1_1-lfs.dll`, after the third install I have `luafilesystem_1_6_2_2-lfs.dll` and get the above mentioned error message. Another `luarocks install luafilesystem` will return to the normal `lfs.dll`.

The error message doesn't happen on Linux, and AFAICT even on Windows everything works as expected, so this is only a cosmetic issue ...

**Comment by mpeterv** [comment] 2016-10-18 19:19
After the second command is executed the state is correct: there is a module for the newer version (call it 0.2) in a non-versioned location and a module for the old one (0.1) in a versioned location. What happens in the third command (installing the newer version again):

1. Old installation of 0.2 is removed.
    1. Versioned module for it doesn't exist.
    2. Non-versioned module exists and is removed.
    3. Versioned module for 0.1 is moved in instead as it is its second provider.
2. 0.2 is reinstalled.
    1. Versioned module already exists (the older version moved in on step 1.iii).
    2. To decide which module should stay in the non-versioned location versions are compared.
    However, Luarocks still thinks that the module is provided by both versions since that was the state
    of the manifest when it was first loaded. Thus, it thinks that the non-versioned module is still
    provided by 0.2. As version comparison is strict, the installed module is considered older and
    is moved into the versioned location.
3. 0.1 is removed.
    1. Versioned module for it doesn't exist.
    2. Non-versioned module exists and is removed.
    3. As on step 1.iii, Luarocks thinks that 0.1 is still the second provider of the module and tries
    to move it in from the versioned location for 0.1, but the file isn't there, causing the error,
    which isn't caught.

End state: 0.2 is there but in versioned location, which is bad (can't be required).

So, the problem is that deploying/removing rocks uses some information from the manifest: which two newest versions provide each module. As the manifest isn't always updated between operations, sometimes wrong information is used, like in this bug. In this case, manifest isn't updated after step 1: removal of the old installation of the same version that's being installed. Another case is removing several versions: if the third command installed a version older than both 0.1 and 0.2, then removing them would cause a similar error, because `delete_versions` called by `remove_other_versions` doesn't update manifest after each deletion.

The fix should be to always update manifest after `repos.delete_version`, at least the in-memory version.

**Comment by hishamhm** [comment] 2016-10-18 21:19
Thank you for the analysis — I just wrote a test case to reproduce this with the suite. I'm working on a fix now.

**Comment by hishamhm** [comment] 2016-10-18 22:22
As per the comment in the commit: @mpeterv, I made a naive implementation of the solution you suggested (just calling make_manifest at the end of delete_version).

It does produce more correct behavior, at the cost of a performance regression. I think the ideal solution would be to make `update_manifest` smarter, so it would handle removal of a rock from the manifest, and use that instead.

In any case, the bug itself is fixed. Can we close this?

**Closed** 2016-10-20 08:44 UTC
