### ISSUE TITLE
luarocks crashed with lmd5 module installed.

### ISSUE THREAD

**Issue by luafan** [keplerproject/luarocks#550] opened 2016-05-05 06:07 UTC
luarocks-5.1 install lmd5 OPENSSL=&lt;your openssl header path&gt;
luarocks-5.1 install &lt;any other module&gt;

Error: LuaRocks 2.3.0 bug (please report at https://github.com/keplerproject/luarocks/issues).
...51/5.1.5_4/libexec/share/lua/5.1/luarocks/fs/lua.lua:738: attempt to call field 'sumhexa' (a nil value)
stack traceback:
	...51/5.1.5_4/libexec/share/lua/5.1/luarocks/fs/lua.lua:738: in function 'get_md5'
	...a51/5.1.5_4/libexec/share/lua/5.1/luarocks/manif.lua:77: in function 'make_rock_manifest'
	...a51/5.1.5_4/libexec/share/lua/5.1/luarocks/build.lua:316: in function 'build_rockspec'
	...ua51/5.1.5_4/libexec/share/lua/5.1/luarocks/make.lua:82: in function <...ua51/5.1.5_4/libexec/share/lua/5.1/luarocks/make.lua:51>
	(tail call): ?
	[C]: in function 'xpcall'
	....5_4/libexec/share/lua/5.1/luarocks/command_line.lua:207: in function 'run_command'
	/usr/local/bin/luarocks-5.1:34: in main chunk
	[C]: ?

**Comment by daurnimator** [comment] 2016-05-05 06:11
Duplicate of #494

**Closed** 2016-05-08 10:41 UTC
