### ISSUE TITLE
Attempt to concatenate field 'root_dir' error

### ISSUE THREAD

**Issue by thefosk** [keplerproject/luarocks#319] opened 2015-03-03 21:42 UTC
I'm experiencing the following error when removing a rock:

```
$ sudo luarocks remove luacheck
Error: LuaRocks 2.2.0 bug (please report at luarocks-developers@lists.sourceforge.net).
/usr/local/share/lua/5.1/luarocks/remove.lua:162: attempt to concatenate field 'root_dir' (a table value)
stack traceback:
	/usr/local/share/lua/5.1/luarocks/remove.lua:162: in function </usr/local/share/lua/5.1/luarocks/remove.lua:140>
	(tail call): ?
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/luarocks/command_line.lua:208: in function 'run_command'
	/usr/local/bin/luarocks:33: in main chunk
	[C]: ?
```

**Comment by daurnimator** [comment] 2015-03-03 21:49
I get this error regularly when I try to remove a package I don't have installed.

**Comment by mpeterv** [comment] 2015-03-04 12:36
Looks like duplicate of #295.

**Comment by hishamhm** [comment] 2015-03-05 01:37
Indeed. It's about time for a new release. I'll see it through.

**Closed by hishamhm** 2015-03-05 01:37 UTC
