### ISSUE TITLE
scm bug

### ISSUE THREAD

**Issue by Sriharsha-reddy** [keplerproject/luarocks#493] opened 2016-02-01 14:33 UTC
Error: LuaRocks scm bug (please report at https://github.com/keplerproject/luarocks/issues).
/home/obiwan/torch/install/share/lua/5.1/luarocks/help.lua:77: module 'luarocks.config_cmd' not found:No LuaRocks module found for luarocks.config_cmd
	no field package.preload['luarocks.config_cmd']
	no file '/home/obiwan/torch/install/share/lua/5.1/luarocks/config_cmd.lua'
	no file '/home/obiwan/torch/install/share/lua/5.1/luarocks/config_cmd/init.lua'
	no file '/home/obiwan/.luarocks/share/lua/5.1/luarocks/config_cmd.lua'
	no file '/home/obiwan/.luarocks/share/lua/5.1/luarocks/config_cmd/init.lua'
	no file './luarocks/config_cmd.lua'
	no file '/home/obiwan/torch/install/share/luajit-2.1.0-beta1/luarocks/config_cmd.lua'
	no file '/usr/local/share/lua/5.1/luarocks/config_cmd.lua'
	no file '/usr/local/share/lua/5.1/luarocks/config_cmd/init.lua'
	no file '/home/obiwan/torch/install/lib/luarocks/config_cmd.so'
	no file '/home/obiwan/.luarocks/lib/lua/5.1/luarocks/config_cmd.so'
	no file '/home/obiwan/torch/install/lib/lua/5.1/luarocks/config_cmd.so'
	no file './luarocks/config_cmd.so'
	no file '/usr/local/lib/lua/5.1/luarocks/config_cmd.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/obiwan/torch/install/lib/luarocks.so'
	no file '/home/obiwan/.luarocks/lib/lua/5.1/luarocks.so'
	no file '/home/obiwan/torch/install/lib/lua/5.1/luarocks.so'
	no file './luarocks.so'
	no file '/usr/local/lib/lua/5.1/luarocks.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/home/obiwan/torch/install/share/lua/5.1/luarocks/help.lua:77: in function </home/obiwan/torch/install/share/lua/5.1/luarocks/help.lua:44>
	[C]: in function 'xpcall'
	...an/torch/install/share/lua/5.1/luarocks/command_line.lua:202: in function 'run_command'
	/home/obiwan/torch/install/bin/luarocks:35: in main chunk
	[C]: at 0x00406670

**Comment by siffiejoe** [comment] 2016-02-01 16:34
This seems to be a duplicate of #485 and torch/luajit-rocks#24.

**Comment by mpeterv** [comment] 2016-02-01 16:39
Renamed #485 to make it easier to find it.

**Closed** 2016-02-01 16:39 UTC
