### ISSUE TITLE
When I run luarocks --help I get this error: module 'luarocks.config_cmd' not found

### ISSUE THREAD

**Issue by manjunaths** [keplerproject/luarocks#485] opened 2016-01-13 12:06 UTC
Error: LuaRocks scm bug (please report at https://github.com/keplerproject/luarocks/issues).
...opencl/torch/install/share/lua/5.1/luarocks/help.lua:77: module 'luarocks.config_cmd' not found:No LuaRocks module found for luarocks.config_cmd
        no field package.preload['luarocks.config_cmd']
        no file '/usr2/manju/Moonshot/DeepLearning/opencl/torch/install/share/lua/5.1/luarocks/config_cmd.lua'
        no file '/usr2/manju/Moonshot/DeepLearning/opencl/torch/install/share/lua/5.1/luarocks/config_cmd/init.lua'
        no file '/usr2/manju/.luarocks/share/lua/5.1/luarocks/config_cmd.lua'
        no file '/usr2/manju/.luarocks/share/lua/5.1/luarocks/config_cmd/init.lua'
        no file './luarocks/config_cmd.lua'
        no file '/usr2/manju/Moonshot/DeepLearning/opencl/torch/install/lib/lua/5.1/luarocks/config_cmd.lua'
        no file '/usr2/manju/Moonshot/DeepLearning/opencl/torch/install/lib/lua/5.1/luarocks/config_cmd/init.lua'
        no file '/usr2/manju/Moonshot/DeepLearning/opencl/torch/install/lib/luarocks/config_cmd.so'
        no file '/usr2/manju/.luarocks/lib/lua/5.1/luarocks/config_cmd.so'
        no file '/usr2/manju/Moonshot/DeepLearning/opencl/torch/install/lib/lua/5.1/luarocks/config_cmd.so'
        no file './luarocks/config_cmd.so'
        no file '/usr2/manju/Moonshot/DeepLearning/opencl/torch/install/lib/lua/5.1/loadall.so'
        no file '/usr2/manju/Moonshot/DeepLearning/opencl/torch/install/lib/luarocks.so'
        no file '/usr2/manju/.luarocks/lib/lua/5.1/luarocks.so'
        no file '/usr2/manju/Moonshot/DeepLearning/opencl/torch/install/lib/lua/5.1/luarocks.so'
        no file './luarocks.so'
        no file '/usr2/manju/Moonshot/DeepLearning/opencl/torch/install/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ...opencl/torch/install/share/lua/5.1/luarocks/help.lua:77: in function <...opencl/torch/install/share/lua/5.1/luarocks/help.lua:44>
        (tail call): ?
        [C]: in function 'xpcall'
        ...orch/install/share/lua/5.1/luarocks/command_line.lua:202: in function 'run_command'
        ...nshot/DeepLearning/opencl/torch/install/bin/luarocks:35: in main chunk
        [C]: ?

Any help ?

**Comment by hishamhm** [comment] 2016-01-13 13:38
How did you install/update LuaRocks? You seem to be missing the config_cmd.lua command, which is here: https://github.com/keplerproject/luarocks/blob/master/src/luarocks/config_cmd.lua

If this is missing, more stuff may be problematic in your install too.

**Comment by siffiejoe** [comment] 2016-01-13 17:37
Once upon a time `config_cmd.lua` was missing from the list of modules to install. This has been fixed in f0aa57e5149233c106f2a791694ae80dbfc62d3d in May 2015. If your install is from before then, reinstalling a more recent version should fix the issue.

**Comment by mharrys** [comment] 2016-01-22 23:00
I got luarocks by installing Torch7 today and I also get this error. It also appears that they use a version that is more recent than May 2015.

**Comment by mharrys** [comment] 2016-01-23 12:22
I removed torch and installed luarocks from this repo and did not have this error, then I removed luarocks and installed torch again but not from master but checked out a random commit two month back and the error was not present. Since @manjunaths has torch in his path it would appear the problem is with how torch does the insallation of luarocks.

For future reference, I installed from commit 7b7156abb266b294bdf2720d97aeab2c27e9d4ef in the torch distro repo.

**Comment by vpong** [comment] 2016-01-23 22:48
I had the same issue. LuaRocks was installed when I installed torch. I didn't uninstall torch, but I just followed the [instructions on installing LuaRocks](https://github.com/keplerproject/luarocks/wiki/Installation-instructions-for-Unix), and it fixed the problem.

**Comment by siffiejoe** [comment] 2016-01-24 12:08
It seems that Torch uses [its own build script][1] for installing LuaRocks, which lacks the `config_cmd.lua` module in its list of LuaRocks modules to install. As a consequence, the LuaRocks installation is broken, but you'll only notice when you try to use the new `luarocks config` command (or when you request its help text). A cursory count suggests that there are five more modules missing (probably some fetchers). Anyway, I think this issue should be closed and another one be opened at the `torch/luajit-rocks` repository.

  [1]: https://github.com/torch/luajit-rocks/blob/0de2b349de78491acb4bfd5c99849f9ecea44639/luarocks/CMakeLists.txt#L86-L98

**Comment by lukeyeager** [comment] 2016-01-26 00:05
I'm seeing the same error when I run `luarocks` with no arguments (thus invoking `--help`):
```
Error: LuaRocks scm bug (please report at https://github.com/keplerproject/luarocks/issues).
...torch/2016-01-25/install/share/lua/5.1/luarocks/help.lua:77: module 'luarocks.config_cmd' not found:No LuaRocks module found for luarocks.config_cmd
	no field package.preload['luarocks.config_cmd']
	no file '/home/lyeager/torch/2016-01-25/install/share/lua/5.1/luarocks/config_cmd.lua'
	no file '/home/lyeager/torch/2016-01-25/install/share/lua/5.1/luarocks/config_cmd/init.lua'
	no file './luarocks/config_cmd.lua'
	no file '/home/lyeager/torch/2016-01-25/install/share/luajit-2.1.0-beta1/luarocks/config_cmd.lua'
	no file '/usr/local/share/lua/5.1/luarocks/config_cmd.lua'
	no file '/usr/local/share/lua/5.1/luarocks/config_cmd/init.lua'
	no file '/home/lyeager/.luarocks/share/lua/5.1/luarocks/config_cmd.lua'
	no file '/home/lyeager/.luarocks/share/lua/5.1/luarocks/config_cmd/init.lua'
	no file './luarocks/config_cmd.so'
	no file '/usr/local/lib/lua/5.1/luarocks/config_cmd.so'
	no file '/home/lyeager/torch/2016-01-25/install/lib/lua/5.1/luarocks/config_cmd.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/lyeager/.luarocks/lib/lua/5.1/luarocks/config_cmd.so'
	no file './luarocks.so'
	no file '/usr/local/lib/lua/5.1/luarocks.so'
	no file '/home/lyeager/torch/2016-01-25/install/lib/lua/5.1/luarocks.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/lyeager/.luarocks/lib/lua/5.1/luarocks.so'
stack traceback:
	[C]: in function 'require'
	...torch/2016-01-25/install/share/lua/5.1/luarocks/help.lua:77: in function <...torch/2016-01-25/install/share/lua/5.1/luarocks/help.lua:44>
	[C]: in function 'xpcall'
	...16-01-25/install/share/lua/5.1/luarocks/command_line.lua:202: in function 'run_command'
	./luarocks:35: in main chunk
	[C]: at 0x00406670
```
I was following less standard instructions: https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildTorch.md

**Comment by manjunaths** [comment] 2016-01-30 06:17
If anyone is still following this thread, doing a 
`luarocks install luarocks`
 seems to fix the issue.

**Comment by manjunaths** [comment] 2016-01-30 06:26
A bug has been filed against the luajit-rocks project as was indicated. This issue can be closed here. 

Thank you.

**Comment by soumith** [comment] 2016-02-02 17:52
thanks for pointing this out, looking into it. Looks like a few cmake fixes are needed.

**Comment by Atcold** [comment] 2016-02-03 17:08
OK, same error here.

**Comment by soumith** [comment] 2016-02-03 17:09
we fixed this in torch trunk. either reinstalling luarocks via: luarocks install luarocks
or reinstalling torch fixes this.
The issue can be closed, and sorry for the noise to this repo.

**Comment by lukeyeager** [comment] 2016-02-03 17:36
Reinstalling torch distro didn't work for me:
```sh
$ git clone https://github.com/torch/distro.git 2016-02-03 --recursive
$ cd 2016-02-03/
$ ./install.sh 
$ install/bin/luarocks
# same error
```
But updating luarocks did:
```
$ install/bin/luarocks install luarocks
# installs version 2.3.0-1
$ install/bin/luarocks
# no error
```

**Comment by soumith** [comment] 2016-02-03 18:31
@lukeyeager forgot to update the distro hashes. done now and tested it out with your exact commands.

**Comment by lukeyeager** [comment] 2016-02-03 18:39
Looks like https://github.com/torch/distro/commit/eaa1786efbefc13be39b472ee3a3fd17430d44ad did the trick - thanks!

**Comment by siffiejoe** [comment] 2016-02-26 15:56
This seems to be resolved.

**Closed by siffiejoe** 2016-02-26 15:56 UTC

**Comment by jbrahy** [comment] 2019-06-13 20:37
Installing from yum on CentOS 7.6.1810 epel installed

Name        : luarocks
Arch        : x86_64
Version     : 2.3.0
Release     : 1.el7

It gives me the same error.
