### ISSUE TITLE
Luarocks pack can't compress?

### ISSUE THREAD

**Issue by geoffleyland** [keplerproject/luarocks#502] opened 2016-02-18 23:02 UTC
I must be doing something wrong, but, with Luarocks master HEAD, `luarocks pack` gets an error when it tries to compress something:
```
$ luarocks pack rockspecs/patengi-scm-1.rockspec 
Cloning into 'lua-patengi'...
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 19 (delta 1), reused 12 (delta 0), pack-reused 0
Receiving objects: 100% (19/19), 7.58 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.

Error: LuaRocks scm bug (please report at https://github.com/keplerproject/luarocks/issues).
/usr/local/share/lua/luarocks/tools/zip.lua:55: attempt to call field 'compress' (a nil value)
stack traceback:
	/usr/local/share/lua/luarocks/tools/zip.lua:55: in function 'write_file_in_zip'
	/usr/local/share/lua/luarocks/tools/zip.lua:125: in function 'add'
	/usr/local/share/lua/luarocks/tools/zip.lua:235: in function 'zip'
	/usr/local/share/lua/luarocks/pack.lua:57: in function 'pack_source_rock'
	/usr/local/share/lua/luarocks/pack.lua:204: in function </usr/local/share/lua/luarocks/pack.lua:195>
	[C]: in function 'xpcall'
	/usr/local/share/lua/luarocks/command_line.lua:206: in function 'run_command'
	/usr/local/bin/luarocks:34: in main chunk
	[C]: at 0x0100001020

```

The offending line, /usr/local/share/lua/luarocks/tools/zip.lua:55, is
```local cbuf = zlib.compress(buf):sub(3, -5)```

As far as I can tell, I'm using the right zlib?
```
luarocks list
...
lua-zlib
   0.4-1 (installed) - /usr/local/lib/luarocks/rocks
...
```
But it doesn't contain a `compress` member, it has a `deflate`.  Is it the wrong zlib?
```
> for k, v in pairs(require"zlib") do print(k, v) end
_COPYRIGHT	Copyright (c) 2009-2010 Brian Maher
adler32	function: 0x0004b6a0
BEST_COMPRESSION	9
crc32	function: 0x0004b6e8
deflate	function: 0x0004b610
_TEST_BUFSIZ	1024
_VERSION	lua-zlib $Id: 3f7186e67a9228def6a9a150ebe8fa6378f4a0a2 $ $Format:%d$
_DESCRIPTION	Yet another binding to the zlib library
version	function: 0x0004b730
inflate	function: 0x0004b658
BEST_SPEED	1
```

**Comment by daurnimator** [comment] 2016-02-18 23:07
Duplicate of https://github.com/keplerproject/luarocks/issues/388

luarocks needs lzlib, it fails if you have lua-zlib installed.

**Comment by ignacio** [comment] 2016-02-18 23:09
Yes. There is an issue about that (#388) which hasn't been addressed yet. You can try what's been proposed there, or you can edit your `config.lua` file and add `fs_use_modules = false`

**Comment by geoffleyland** [comment] 2016-02-18 23:10
> On 19/02/2016, at 12:07 PM, daurnimator <notifications@github.com> wrote:
> 
> Duplicate of #388
> 
> luarocks needs lzlib, it fails if you have lua-zlib installed.

Thanks!  I should have searched the issues with "zlib" rather than "pack".  I wonder what depends on lua-zlib?

**Closed** 2016-02-18 23:10 UTC
