### ISSUE TITLE
Prefer shared libraries

### ISSUE THREAD

**Issue by v1993** [keplerproject/luarocks#928] opened 2018-10-04 11:23 UTC
Currently, luarocks passes `-DLUALIB=liblua5.2.a` to cmake, which is IMHO pretty bad for size/updating/etc. What about using shared library when aviable?

I think that cause of problem is that external_deps_patterns look like that:

    external_deps_patterns = {
    	bin = { "?" };
    	lib = { "lib?.a"; "lib?.so"; "lib?.so.*"; };
    	include = { "?.h" };
    }
What if `external_deps_patterns.lib` will be ordered with `.a` at end?

**Comment by v1993** [comment] 2018-10-04 13:27
@hishamhm Adding that to config file doesn't change results of `luarocks.config`.

**Comment by siffiejoe** [comment] 2018-10-04 14:47
Is the Lua library an external dependency? I believe it is detected for Windows in `install.bat` (and has a default value in `luarocks.core.cfg`), and on Unixes it isn't used anyway (the interpreter exports the Lua API).

And on Windows it prefers the `.lib` suffix (for import libraries) or `.dll`. A static Lua library and dynamic loading of extension modules don't mix on Windows.

**Comment by hishamhm** [comment] 2018-10-04 17:54
> I believe it is detected for Windows in install.bat 

In LR3 we moved that detection to runtime using the external dependencies mechanism.

**Comment by hishamhm** [comment] 2018-10-04 17:55
> @hishamhm Adding that to config file doesn't change results of luarocks.config.

Odd, I tried it here and it did change the output of `luarocks config`. Run `luarocks` with no arguments and check the path of the config files to make sure you're using that is marked as `(ok)`.

**Comment by hishamhm** [comment] 2024-02-19 17:51
Closing this due to failure to reproduce and lack of activity. Feel free to reopen if the problem reappears!

**Closed as completed by hishamhm** 2024-02-19 17:51 UTC
