### ISSUE TITLE
fbcunn installation failed and then luarocks crashed.

### ISSUE THREAD

**Issue by taineleau** [keplerproject/luarocks#512] opened 2016-03-09 10:11 UTC
Hi,

> 
> COMMANDS
> 	build
> 		Build/compile a rock.
> 
> Error: LuaRocks scm bug (please report at https://github.com/keplerproject/luarocks/issues).
> /usr/local/torch/install/share/lua/5.1/luarocks/help.lua:77: module 'luarocks.config_cmd' not found:No LuaRocks module found for luarocks.config_cmd
> 	no field package.preload['luarocks.config_cmd']
> 	no file '/usr/local/torch/install/share/lua/5.1/luarocks/config_cmd.lua'
> 	no file '/usr/local/torch/install/share/lua/5.1/luarocks/config_cmd/init.lua'
> 	no file '/home/htc/.luarocks/share/lua/5.1/luarocks/config_cmd.lua'
> 	no file '/home/htc/.luarocks/share/lua/5.1/luarocks/config_cmd/init.lua'
> 	no file './luarocks/config_cmd.lua'
> 	no file '/usr/local/torch/install/share/luajit-2.1.0-beta1/luarocks/config_cmd.lua'
> 	no file '/usr/local/share/lua/5.1/luarocks/config_cmd.lua'
> 	no file '/usr/local/share/lua/5.1/luarocks/config_cmd/init.lua'
> 	no file '/home/taineleau/.luarocks/share/lua/5.1/luarocks/config_cmd.lua'
> 	no file '/home/taineleau/.luarocks/share/lua/5.1/luarocks/config_cmd/init.lua'
> 	no file '/usr/local/torch/install/lib/luarocks/config_cmd.so'
> 	no file '/home/htc/.luarocks/lib/lua/5.1/luarocks/config_cmd.so'
> 	no file '/usr/local/torch/install/lib/lua/5.1/luarocks/config_cmd.so'
> 	no file './luarocks/config_cmd.so'
> 	no file '/usr/local/lib/lua/5.1/luarocks/config_cmd.so'
> 	no file '/usr/local/lib/lua/5.1/loadall.so'
> 	no file '/home/taineleau/.luarocks/lib/lua/5.1/luarocks/config_cmd.so'
> 	no file '/usr/local/torch/install/lib/luarocks.so'
> 	no file '/home/htc/.luarocks/lib/lua/5.1/luarocks.so'
> 	no file '/usr/local/torch/install/lib/lua/5.1/luarocks.so'
> 	no file './luarocks.so'
> 	no file '/usr/local/lib/lua/5.1/luarocks.so'
> 	no file '/usr/local/lib/lua/5.1/loadall.so'
> 	no file '/home/taineleau/.luarocks/lib/lua/5.1/luarocks.so'
> stack traceback:
> 	[C]: in function 'require'
> 	/usr/local/torch/install/share/lua/5.1/luarocks/help.lua:77: in function </usr/local/torch/install/share/lua/5.1/luarocks/help.lua:44>
> 	[C]: in function 'xpcall'
> 	...al/torch/install/share/lua/5.1/luarocks/command_line.lua:202: in function 'run_command'
> 	/usr/local/torch/install/bin/luarocks:35: in main chunk
> 	[C]: at 0x00405ea0`

following `https://github.com/facebook/fbcunn/blob/master/INSTALL.md` and got message as above.

**Comment by daurnimator** [comment] 2016-03-09 10:19
Duplicate of https://github.com/keplerproject/luarocks/issues/485

**Comment by mpeterv** [comment] 2016-06-17 16:37
And the original issue was resolved.

**Closed by mpeterv** 2016-06-17 16:37 UTC
